engine:
  name: tofu
  version: 1.8.4
cost_estimation:
  enabled: false

dirs:
  core:
    when_modified:
      file_patterns: [ "layers/core/*.tf" ]


hooks:
  apply:
    post:
      - type: env
        method: source
        cmd: [ '$TERRATEAM_ROOT/scripts/export_public_outputs.sh' ]

workflows:
  - tag_query: ""
    plan:
      - type: env
        method: source
        cmd: [ '$TERRATEAM_ROOT/scripts/s3_backend.sh' ]
      - type: env
        name: TF_LOG_CORE
        cmd: ['echo', 'DEBUG']
      - type: env
        name: TF_LOG_PROVIDER
        cmd: ['echo', 'DEBUG']
      - type: init
        extra_args: [ '-backend-config=backend.hcl' ]
      - type: plan

    apply:
      - type: env
        method: source
        cmd: [ '$TERRATEAM_ROOT/scripts/s3_backend.sh' ]
      - type: env
        name: TF_LOG_CORE
        cmd: ['echo', 'DEBUG']
      - type: env
        name: TF_LOG_PROVIDER
        cmd: ['echo', 'DEBUG']
      - type: init
        extra_args: [ '-backend-config=backend.hcl' ]
      - type: apply
